# nixpacks.toml

[phases.setup]
aptPkgs = [
  "libnss3",
  "libnspr4",
  "libdbus-glib-1-2",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libcups2",
  "libatspi2.0-0",
  "libxcomposite1",
  "libxdamage1",
  "libxrandr2",
  "libgbm1",
  "libxkbcommon0",
  "libpango-1.0-0",
  "libcairo2",
  "libasound2",
  "libxtst6",
  "libglib2.0-0"
]
